title:  Nuri Çilengir - Blog
description: Disconnetus Erectus
author: Nuri Çilengir
github: https://github.com/derectus
about: I'm application security & software development enthusiast. Also, I work as a translator and writer in the Arka Kapı Magazine.
disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "#"
    - icon: fa-linkedin
      link: "#"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/agusmakmun"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: About
      url: /about/
    - text: XML Feed
      url: /feed.xml

url: "https://derectus.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
