title:  Blog
description: Disconnetus Erectus
author: Nuri Çilengir
github: https://github.com/derectus
about: I'm application security & software development enthusiast. Also, I work as a translator and writer in the Arka Kapı Magazine.
disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:

    - icon: fa-twitter
      link: "https://twitter.com/der3ctus"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/cilengirnuri/"
    - icon: fa-reddit
      link: "https://www.reddit.com/user/erectustd"
    - icon: fa-github
      link: "https://github.com/derectus"

share:
  twitter_username: der3ctus

urls:
    - text: About
      url: /about/
    - text: XML Feed
      url: /feed.xml

url: "https://derectus.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
